language: cpp
sudo: enabled
dist: trusy
compiler:
- gcc
os:
- linux
before_install:
- echo $LANG
- echo $LC_ALL
- sudo apt install beignet-opencl-icd 
script:
- make OPENCL_HEADERS=/usr/lib/x86_64-linux-gnu/beignet/include/ LIBOPENCL=/usr/lib/x86_64-linux-gnu/beignet/ LDLIBS="-lcl -lrt"
