language: cpp
sudo: enabled
dist: xenial
compiler:
- gcc
os:
- linux
before_install:
- sudo apt-get update
- sudo apt-get install beignet-opencl-icd opencl-headers
- sudo ldconfig
script:
- make && make test
